version: '3'
services:
  modlang_frontend:
    build:
      context: ./Frontend
      # target: dev # dev
    restart: always
    image: modlang_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=1day-project
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=https://modlangtum-api.vercel.app
