@startuml Manage User (GET)

header Job Fair Sequence Diagram
footer Page %page% of %lastpage%
title "Manage User (GET)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:auth" as routerUser
participant "<<middleware>>\n:auth" as authMiddleware
participant "<<controllers>>\n:auth" as controllersUser
participant "<<model>>\n:User" as modelUser
database "<<MongoDB>>\n:users" as UserDatabase

client->server ++:req.get('/auth/me')
server->routerUser ++:app.use('/auth',user)
routerUser -> authMiddleware ++:protect()
routerUser -> controllersUser ++:getMe()
controllersUser->modelUser ++:findById(req.user.id)
modelUser ->UserDatabase ++: UserSchema
UserDatabase --> modelUser --:user
controllersUser <-- modelUser --:user
controllersUser->client --:response

@enduml
